{{- $url := printf "%s" .Values.global.appBaseUrl }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.namespace }}-root-ingress
  namespace: {{ .Values.ingress.namespace }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: private
  rules:
    - host: {{ $url }}
      http:
        paths:
          - backend:
              service:
                name: app-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: server-svc
                port:
                  number: 80
            path: /graphql
            pathType: Prefix
          - backend:
              service:
                name: usage-svc
                port:
                  number: 80
            path: /usage
            pathType: Prefix
