image:
  repository: supertokens/supertokens-postgresql
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "3.14"

replicaCount: 1
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

global:
  postgresql:
    auth:
      database: engage-hive
      user: postgres

  apiKey:
    # -- enable the use of API Keys with supertokens-core
    enabled: true
    # -- list of API Keys to load and use with supertokens-core
    key: "yourApiKey"

database:
  # -- database port
  port: 5432
  # -- database host
  host: postgres-postgresql


service:
  port: 3567
  targetPort: 3567
  nodePort: ""
  type: ClusterIP

# -- Time in seconds for how long an access token is valid for
accessTokenValidity: 3600

# -- If true, allows for immediate revocation of any access token. Keep in mind that setting this to true will result in a db query for each API call that requires authentication.
accessTokenBlacklisting: true

# -- If this is set to true, the JWT (access token) signing key will change every fixed interval of time.
accessTokenSigningKeyDynamic: true

# -- Time in hours for how frequently the JWT (access token) signing key will change. This value only makes sense if "accessTokenSigningKeyDynamic" is true.
accessTokenSigningKeyUpdateInterval: 168

# -- Time in mins for how long a refresh token is valid for.
refreshTokenValidity: 144000

# -- Time in milli-seconds for how long a password reset token is valid for.
passwordResetTokenLifetime: 3600000

# -- Time in milli-seconds for how long an email verification token is valid for.
emailVerificationTokenLifetime: 86400000

# -- The maximum number of code input attempts per login before the user needs to restart.
passwordlessMaxCodeInputAttempts: 5

# -- Time in milliseconds for how long a passwordless code is valid for.
passwordlessCodeLifetime: 900000

basePath: ""

disableTelemetry: false

maxServerPoolSize: 10

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
# fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
# runAsUser: 1000

# -- limit and requests for resources for supertokens-core container
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
#   memory: 128Mi

autoscaling:
  # -- enable autoscaling of replicas
  enabled: false
  # -- minimal replica count when autoscaling
  minReplicas: 1
  # -- maximum replica count when autoscaling
  maxReplicas: 100
  # -- target CPU usage before autoscaling
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
# nodeSelector: {}

# tolerations: []

# affinity: {}
# podAntiAffinity:
#   preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 1
#       podAffinityTerm:
#         labelSelector:
#           matchExpressions:
#             - key: "app.kubernetes.io/name"
#               operator: In
#               values:
#                 - supertokens
#         topologyKey: kubernetes.io/hostname
