name: Integration Tests
on:
  pull_request:
    branches:
      - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - uses: actions/cache@v3
        name: Turbo cache
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-cache-v1-${{ hashFiles('yarn.lock') }}

      - name: Generate Types
        run: yarn graphql:generate

      - name: Build
        run: yarn workspace integration-tests run build-and-pack
        env:
          NEXT_PUBLIC_STRIPE_PUBLIC_KEY: ${{ secrets.TEST_STRIPE_PUBLIC_KEY }}

      - name: Pull images
        run: docker-compose -f integration-tests/docker-compose.yml pull

      - name: Integration Tests
        run: yarn workspace integration-tests run dockest
        env:
          AUTH0_DOMAIN: ${{ secrets.TEST_AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.TEST_AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.TEST_AUTH0_CLIENT_SECRET }}
          AUTH0_USER_PASSWORD: ${{ secrets.AUTH0_TESTING_USER_PASSWORD }}
          AUTH0_USER_MAIN_EMAIL: contact@the-guild.dev
          AUTH0_USER_EXTRA_EMAIL: contact+extra@the-guild.dev
          AUTH0_SECRET: ${{ secrets.TEST_AUTH0_SECRET }}
          AUTH0_AUDIENCE: ${{ secrets.TEST_AUTH0_AUDIENCE }}
          AUTH0_CONNECTION: Username-Password-Authentication
          STRIPE_SECRET_KEY: ${{ secrets.TEST_STRIPE_SECRET_KEY }}

      - name: Dockest logs
        if: always()
        run: cat integration-tests/*.log
