on:
  workflow_call:

jobs:
  eslint-and-prettier:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: setup environment
        uses: ./.github/actions/setup
        with:
          actor: lint
          cacheNext: false
          cacheTurbo: false

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: lint .env.template files
        run: bun run lint:env-template

      - name: Cache ESLint and Prettier
        uses: actions/cache@v3
        with:
          path: |
            .eslintcache
            node_modules/.cache/prettier
          key: lint-cache-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            lint-cache-${{ hashFiles('**/pnpm-lock.yaml') }}-

      - name: eslint
        id: eslint
        run: |
          bun run lint || \
          ( \
            echo "" && \
            echo "To fix it, run" && \
            echo "$ pnpm run lint:fix" && \
            echo "" && \
            exit 1 \
          )
        env:
          TIMING: 'true'

      - name: prettier
        id: prettier
        shell: sh
        run: |
          bun run lint:prettier || \
          ( \
            echo "" && \
            echo "To fix it, run" && \
            echo "$ pnpm run prettier" && \
            echo "" && \
            exit 1 \
          )

      - name: Generate Types
        run: bun run graphql:generate

      - name: Operation Check
        run: |
          bunx graphql-inspector validate \
            "packages/web/app/{src,pages}/**/*.{graphql,tsx}|packages/libraries/cli/**/*.graphql|packages/web/app/src/lib/**/*.ts" \
            "packages/**/module.graphql.ts" \
            --maxDepth=20 \
            --maxAliasCount=20 \
            --maxDirectiveCount=20 \
            --maxTokenCount=850
