apiVersion: v1
kind: Service
metadata:
  name: {{- include "supertokens.fullname" . | indent 1 }}
  labels: 
{{ include "supertokens.labels" . | indent 4}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      {{ if .Values.service.nodePort -}}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
{{ include "supertokens.selectorLabels" . |  indent 4}}
